'''
try and except:

try:

…

except:

…

oque passar pelo try e tiver algum erro, 
ele pula direto para o except mesmo com o erro, 
ou seja, o programa nao para mesmo com erro, 
so continua porem pula a etapa do erro
'''